services:
  openvpn:
    image: darktool/openvpn
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - 1194:1194/udp
      - 1194:1194/tcp
    sysctls:
      net.ipv4.ip_forward: 1
    restart: always
